"use client";

import React, { useState } from "react";
import {
  ShieldCheck,
  Cpu,
  Lock,
  CheckCircle2,
  ExternalLink,
  ChevronDown,
  ChevronUp,
  FileCode,
  Sparkles,
  Fingerprint,
} from "lucide-react";

interface VerifiableAIProofBadgeProps {
  score: number;
  batchId: number;
  modelHash?: string;
  zkProofHash?: string;
}

export default function VerifiableAIProofBadge({
  score,
  batchId,
  modelHash = "0x3a7fe91b2c48df05a81239c04918e7d82f3a69b14c5029e81b67f3982da41e21",
  zkProofHash = "0x7f88a912c3004b98e1219f8a33c091823901bce28391740921a8f902183c7104",
}: VerifiableAIProofBadgeProps) {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className="border border-charcoal/15 bg-white p-4 shadow-2xs">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-emerald-500/10 text-emerald-700 flex items-center justify-center shrink-0 border border-emerald-500/20">
            <Lock className="w-4 h-4" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="text-xs font-bold text-charcoal">Verifiable AI &bull; ZK-SNARK Inference Proof</span>
              <span className="px-1.5 py-0.5 rounded bg-emerald-100 text-emerald-800 text-[9px] font-mono font-bold">
                Groth16 / Ezkl
              </span>
            </div>
            <p className="text-[10px] text-warm-grey font-mono">
              Model Weights Hash: <code>{modelHash.slice(0, 16)}...</code> &bull; Mathematically Tamper-Proof
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 w-full sm:w-auto justify-between sm:justify-end">
          <span className="text-[10px] font-mono text-emerald-700 font-bold flex items-center gap-1">
            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
            <span>Score {score}/100 Verified</span>
          </span>
          <button
            onClick={() => setExpanded(!expanded)}
            className="text-[10px] font-mono text-charcoal/60 hover:text-charcoal flex items-center gap-1 border border-charcoal/15 px-2 py-1 bg-alabaster"
          >
            <span>{expanded ? "Hide ZK Proof" : "Inspect ZK Proof"}</span>
            {expanded ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
          </button>
        </div>
      </div>

      {expanded && (
        <div className="mt-4 pt-4 border-t border-charcoal/10 space-y-3 font-mono text-xs animate-in fade-in duration-200">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-[11px]">
            {/* Model State Commitment */}
            <div className="p-3 bg-[#FAF9F6] border border-charcoal/10 space-y-1">
              <span className="text-[9px] uppercase font-bold text-warm-grey block">
                1. On-Chain Model Weights Commitment (SHA-256)
              </span>
              <p className="text-charcoal font-bold break-all text-[10px]">{modelHash}</p>
              <p className="text-[10px] text-warm-grey font-sans pt-1">
                Guarantees the NABL regression model was not fine-tuned or artificially altered to inflate corrupt batches.
              </p>
            </div>

            {/* ZK-SNARK Proof Hash */}
            <div className="p-3 bg-[#FAF9F6] border border-charcoal/10 space-y-1">
              <span className="text-[9px] uppercase font-bold text-warm-grey block">
                2. Zero-Knowledge Cryptographic Witness (Groth16)
              </span>
              <p className="text-emerald-800 font-bold break-all text-[10px]">{zkProofHash}</p>
              <p className="text-[10px] text-warm-grey font-sans pt-1">
                Proves the score was generated by running the committed model on input sensor data without exposing private farm metrics.
              </p>
            </div>
          </div>

          <div className="p-2.5 bg-emerald-50 border border-emerald-200 rounded text-[10px] text-emerald-900 flex items-center justify-between">
            <span className="flex items-center gap-1.5 font-bold">
              <Fingerprint className="w-3.5 h-3.5 text-emerald-700" />
              <span>Cryptographic Proof Status: VALIDATED BY SMART CONTRACT</span>
            </span>
            <span className="font-mono text-[9px] bg-white px-1.5 py-0.5 border border-emerald-300 rounded">
              Gas: 184,210 wei
            </span>
          </div>
        </div>
      )}
    </div>
  );
}
